# Generated by Django 4.1.1 on 2022-10-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConcertName', models.CharField(max_length=100)),
                ('VenueName', models.CharField(max_length=50)),
                ('MaxParticipants', models.IntegerField()),
                ('ConcertDate', models.DateField()),
                ('Location', models.CharField(max_length=100)),
                ('singer', models.ManyToManyField(to='registration.singer')),
            ],
        ),
    ]
