# Generated by Django 4.1.1 on 2022-10-16 07:42

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ArtistName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('YearsActive', models.IntegerField(default=1)),
                ('Birthdate', models.DateField()),
                ('DebutDate', models.DateField()),
                ('isActor', models.BooleanField(default=0)),
                ('isSinger', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('artist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.artist')),
                ('nationality', models.CharField(max_length=30)),
                ('specialization', multiselectfield.db.fields.MultiSelectField(choices=[('T', 'Theatre Acting'), ('TV', 'TV Acting'), ('F', 'Film Acting'), ('VO', 'Voice Over Acting'), ('C', 'Commercials Acting'), ('EB', 'Extra/Background Acting')], max_length=20)),
            ],
            bases=('registration.artist',),
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('artist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.artist')),
                ('Genre', multiselectfield.db.fields.MultiSelectField(choices=[('KP', 'KPop'), ('P', 'Pop'), ('HHR', 'Hip-Hop Rap'), ('C', 'Country'), ('RB', 'Rhythm and Blues'), ('F', 'Folk'), ('J', 'Jazz'), ('HM', 'Heavy Metal'), ('EDM', 'Electronic Dance Music'), ('S', 'Soul'), ('F', 'Funk'), ('R', 'Reggae'), ('D', 'Disco'), ('PR', 'Punk Rock'), ('CL', 'Classical'), ('H', 'House'), ('T', 'Techno'), ('IR', 'Indie Rock'), ('G', 'Grunge'), ('A', 'Ambient'), ('R', 'Reggae'), ('S', 'Soul'), ('F', 'Funk'), ('R', 'Reggae'), ('G', 'Gospel'), ('LM', 'Latin Music'), ('GM', 'Grime'), ('T', 'Trap'), ('PK', 'Psychedelic Rock')], max_length=30)),
                ('Instruments', multiselectfield.db.fields.MultiSelectField(choices=[('AG', 'Acoustic Guitar'), ('BJ', 'Banjo'), ('B', 'Bass'), ('CL', 'Cello'), ('C', 'Clarinet'), ('EG', 'Electric Guitar'), ('D', 'Drums'), ('F', 'Flute'), ('PKO', 'Piano/Keyboard/Organ'), ('S', 'Saxophone'), ('T', 'Trumpet'), ('U', 'Ukelele'), ('V', 'Voice only'), ('V', 'Violin')], max_length=20)),
                ('FandomName', models.CharField(max_length=50)),
            ],
            bases=('registration.artist',),
        ),
    ]
