# Generated by Django 4.1.1 on 2022-10-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='Birthdate',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='DebutDate',
        ),
    ]
