# Generated by Django 4.1.1 on 2022-10-16 07:42

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ArtistName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('YearsActive', models.IntegerField(default=1)),
                ('isActor', models.BooleanField(default=False)),
                ('isSinger', models.BooleanField(default=False)),
                ('Birthdate', models.DateField()),
                ('DebutDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('artist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='star.artist')),
                ('nationality', models.CharField(max_length=30)),
                ('specialization', multiselectfield.db.fields.MultiSelectField(choices=[('T', 'Theatre Acting'), ('TV', 'TV Acting'), ('F', 'Film Acting'), ('VO', 'Voice Over Acting'), ('C', 'Commercials Acting'), ('EB', 'Extra/Background Acting')], max_length=20)),
            ],
            bases=('star.artist',),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmname', models.CharField(max_length=50)),
                ('dateRelease', models.DateField()),
                ('actorRole', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('actor', models.ManyToManyField(to='star.actor')),
            ],
        ),
    ]
