# Generated by Django 4.1.1 on 2022-10-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformName', models.CharField(max_length=30)),
                ('yearEstablished', models.CharField(max_length=4)),
                ('ranking', models.IntegerField()),
                ('singer', models.ManyToManyField(to='registration.singer')),
            ],
        ),
    ]
