# Generated by Django 4.1.1 on 2022-10-06 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('ArtistName', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('YearsActive', models.IntegerField(default=1)),
                ('isActor', models.BooleanField(default=False)),
                ('isSinger', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('artist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promotion.artist')),
                ('Genre', models.CharField(choices=[('KP', 'KPop'), ('P', 'Pop'), ('HHR', 'Hip-Hop Rap'), ('C', 'Country'), ('RB', 'Rhythm and Blues'), ('F', 'Folk'), ('J', 'Jazz'), ('HM', 'Heavy Metal'), ('EDM', 'Electronic Dance Music'), ('S', 'Soul'), ('F', 'Funk'), ('R', 'Reggae'), ('D', 'Disco'), ('PR', 'Punk Rock'), ('CL', 'Classical'), ('H', 'House'), ('T', 'Techno'), ('IR', 'Indie Rock'), ('G', 'Grunge'), ('A', 'Ambient'), ('R', 'Reggae'), ('S', 'Soul'), ('F', 'Funk'), ('R', 'Reggae'), ('G', 'Gospel'), ('LM', 'Latin Music'), ('GM', 'Grime'), ('T', 'Trap'), ('PK', 'Psychedelic Rock')], max_length=3)),
                ('FandomName', models.CharField(max_length=50)),
                ('IsSolo', models.BooleanField(default=False)),
                ('IsGroup', models.BooleanField(default=False)),
            ],
            bases=('promotion.artist',),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platformName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('yearEstablished', models.BigIntegerField()),
                ('ranking', models.IntegerField()),
                ('singer', models.ManyToManyField(to='promotion.singer')),
            ],
        ),
    ]
